export enum ActionType {

  //flags
  CLOSE_INTER_AD = "CLOSE_INTER_AD",
  SHOW_INTER_AD = "SHOW_INTER_AD",
  GET_PRODUCTS = "GET_PRODUCTS",
  REMOVE_ADS = "REMOVE_ADS",
  TOAST_OFF = "TOAST_OFF",
  TOAST = "TOAST",

   //auth
   USER_LOADING = "USER_LOADING",
   USER_LOADED = "USER_LOADED",
   LOGIN_FAILED = "LOGIN_FAILED",
   LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL",
   LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL",
   AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
   AUTO_LOGIN_FAILED = "AUTO_LOGIN_FAILED",
   AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS",
   AUTO_LOGIN = "AUTO_LOGIN",
   USERNAME_SUCCESS = "USERNAME_SUCCESS",
   PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS",

   //Homes
   GET_HOMES = "GET_HOMES",
   SAVE_HOME = "SAVE_HOME",

  //Tasks
  COMPLETE_TASK = "COMPLETE_TASK",
}
